import type { Role } from "./types.js";

// Every mutating or sensitive route declares one of these permission strings.
// Keeping the matrix in one file makes "who can do what" auditable at a glance.
// This is also the single source of truth for docs/NOVA_ROADMAP.md's RBAC
// permission matrix — that table is generated by hand from this file, so if
// you change something here, update the doc too.
//
// budget:* permissions are declared now (Phase 1) even though the budgeting
// module itself is Phase 2 — this lets the RBAC shape for that module be
// reviewed and locked in ahead of building it, rather than bolting
// permissions on after the fact.
export const PERMISSIONS = [
  "accounts:read",
  "accounts:write",
  "journal:read",
  "journal:post",
  "journal:reverse",
  "period:close",
  "student:read",
  "student:write",
  "invoice:read",
  "invoice:create",
  "payment:record",
  "supplier:read",
  "supplier:write",
  "ap:invoice:create",
  "ap:payment:record",
  "report:view",
  "audit:view",
  "user:read",
  "user:manage",
  "payroll:admin",
  "budget:create",
  "budget:submit",
  "budget:review",
  "budget:approve",
  "management:view",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL: Permission[] = [...PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  // System Administrator — full access.
  admin: ALL,

  // Vice-Chancellor — consolidates the former "Finance Manager" and
  // "Principal" roles into one: approves transactions, budgets, and
  // journals; runs reports; manages finance users; sees Management
  // Accounts (KPIs + approvals queue). (Principal's old permission set —
  // report:view, student:read, user:read, budget:approve, management:view
  // — was already a strict subset of Finance Manager's, so this list is
  // simply the union of both.)
  vice_chancellor: [
    "accounts:read",
    "accounts:write",
    "journal:read",
    "journal:post",
    "journal:reverse",
    "period:close",
    "student:read",
    "student:write",
    "invoice:read",
    "invoice:create",
    "payment:record",
    "supplier:read",
    "supplier:write",
    "ap:invoice:create",
    "ap:payment:record",
    "report:view",
    "user:read",
    "audit:view",
    "payroll:admin",
    "budget:review",
    "budget:approve",
    "management:view",
  ],

  // Accounts Officer (formerly "finance_clerk") — day-to-day transaction
  // processing: payments, invoices, receivables and payables. Cannot
  // reverse posted journals, close periods, or reach payroll admin.
  accounts_officer: [
    "accounts:read",
    "journal:read",
    "journal:post",
    "student:read",
    "student:write",
    "invoice:read",
    "invoice:create",
    "payment:record",
    "supplier:read",
    "supplier:write",
    "ap:invoice:create",
    "ap:payment:record",
    "report:view",
    "user:read",
  ],

  // Bursar — student accounts, billing, and receipting only.
  bursar: [
    "accounts:read",
    "student:read",
    "student:write",
    "invoice:read",
    "invoice:create",
    "payment:record",
    "report:view",
    "user:read",
  ],

  // Auditor — read-only across the board, including the audit trail itself.
  // Cannot edit or delete anything, by omission: no write permission appears
  // in this list.
  auditor: [
    "accounts:read",
    "journal:read",
    "student:read",
    "invoice:read",
    "supplier:read",
    "report:view",
    "audit:view",
    "user:read",
  ],

  // IT Administrator — user directory + audit log only. Not part of the
  // Nova spec's named role list, kept because someone needs to manage
  // accounts without touching financial data.
  it_admin: ["user:manage", "user:read", "audit:view"],

  // Budget Officer — creates budgets, submits revisions, views reports.
  // Cannot approve its own submissions (see budget:approve on
  // vice_chancellor/admin only) — separation of duties.
  budget_officer: ["accounts:read", "report:view", "user:read", "budget:create", "budget:submit"],
};

export function roleHasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
